# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '230509.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import *
from PyQt5 import uic
from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QKeySequence,QPixmap, QColor
from PyQt5.QtWidgets import QLabel, QApplication, QWidget, QVBoxLayout


form_class = uic.loadUiType(f'./RDM_UI.ui')[0]

#화면을 띄우는데 사용되는 Class 선언            print(e)

class WindowClass(QMainWindow, form_class) :
    def __init__(self) :
        super().__init__()
        self.setupUi(self)
        self.setFixedSize(400,275)
        self.action_patchnote.triggered.connect(lambda : self.파일열기("패치노트_RDM.txt"))
        self.print_log("실행 가능")

#복붙시작◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈
        self.set_data_path()
        self.set_result_path()


        self.btn_datapath.clicked.connect(self.select_data_file)
        self.btn_datapath_2.clicked.connect(lambda : self.파일열기(self.input_datapath.text()))
        self.btn_execute.clicked.connect(self.activate)

        self.input_datapath.setAcceptDrops(True)
        self.input_datapath.dragEnterEvent = self.drag_enter_event
        self.input_datapath.dropEvent = self.drop_event

        self.combox_country.currentTextChanged.connect(self.set_data_path)
        self.combox_contents.currentTextChanged.connect(self.set_data_path)

        self.combox_contents.currentTextChanged.connect(self.set_result_path)
        self.combox_doctype.currentTextChanged.connect(self.set_result_path)

        self.dateedit.setDate(QDate.currentDate())

        self.btn_resultpath.clicked.connect(self.select_data_file)
        self.btn_resultpath_2.clicked.connect(lambda : self.파일열기(self.input_resultpath.text()))    

#기본동작■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

    def select_data_file(self):
        # Open a file dialog to select the data file
        file_filter = "Video files (*.mp4 *.mkv)"
        file_filter = "엑셀 파일 (*.xlsx)"

        data_file, _ = QFileDialog.getOpenFileName(self,"데이터 파일 선택", filter= file_filter)
        self.input_datapath.setText(data_file)

    def drag_enter_event(self, event):
        # 드래그앤드랍 가능한 MIME 타입인지 체크
        if event.mimeData().hasUrls():
            event.accept()
        else:
            event.ignore()
    
    def drop_event(self, event):
        # 파일 경로를 가져와서 QLineEdit에 입력
        urls = event.mimeData().urls()
        file_path = urls[0].toLocalFile()
        self.input_datapath.setText(file_path)

    def set_data_path(self):
        contents = self.combox_contents.currentText()
        country = self.combox_country.currentText()

        self.input_datapath.setText(f"{contents}DATA_{country}.xlsx")

    def set_result_path(self):
        contents = self.combox_contents.currentText()
        document_type = self.combox_doctype.currentText()
        
        result_path = f"{contents}_{document_type}"

        self.input_resultpath.setText(result_path)
            
        if not os.path.isdir(result_path) :
            os.mkdir(result_path)

    def 파일열기(self,filePath):
        try:
            os.startfile(filePath)
        except : 
            print("파일 없음 : "+filePath)    

    def print_log(self, log): # / - \ / - \ / ㅡ ㄷ
        self.progressLabel.setText(log)
        QApplication.processEvents()

#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
    def activate(self):

        
        result_path = self.input_resultpath.text()
        target_date = self.dateedit.text()
        data_file_name = self.input_datapath.text()
        result_file_name = ""

        try:

            if self.combox_contents.currentText() == "유료상점" :
                if self.combox_doctype.currentText() == "CheckList" :
                    self.print_log("데이터 추출 중...")
                    data = ClCash.extract_data_cashshop(data_file_name, self.dateedit.text())
                    self.print_log("데이터 쓰는 중...")
                    result_file_name = ClCash.write_data_cashshop_inspection(data,result_path,self.checkBox_2.isChecked())
                    self.print_log("데이터 정리 중...")
                    ClCash.postprocess_cashshop(result_file_name)
                elif self.combox_doctype.currentText() == "TestCase" :
                    self.print_log("데이터 추출 중...")
                    data = ClCash.extract_data_cashshop(data_file_name, self.dateedit.text())
                    self.print_log("데이터 쓰는 중...")
                    result_file_name = ClCash.write_data_cashshop(data,result_path)
                    self.print_log("데이터 정리 중...")
                    ClCash.postprocess_cashshop(result_file_name)


            elif self.combox_contents.currentText() == "이벤트" :
                if self.combox_doctype.currentText() == "CheckList" :
                    self.print_log("데이터 추출 중...")
                    data = ClEvent.extract_data(data_file_name, self.dateedit.text())
                    self.print_log("데이터 쓰는 중...")
                    result_file_name = ClEvent.write_data(data,result_path)
                    self.print_log("데이터 정리 중...")
                    ClEvent.postprocess_cashshop(result_file_name)
                # elif self.combox_doctype.currentText() == "TestCase" :
                #     self.print_log("데이터 추출 중...")
                #     data = ClCash.extract_data_cashshop(data_file_name, self.dateedit.text())
                #     self.print_log("데이터 쓰는 중...")
                #     result_file_name = ClCash.write_data_cashshop(data,result_path)
                #     self.print_log("데이터 정리 중...")
                #     ClCash.postprocess_cashshop(result_file_name)

        







            self.print_log("문서 여는 중...")
            os.startfile(os.path.normpath(result_file_name))
            self.print_log("실행 가능")


        except PermissionError:
            self.print_log(f"문서를 닫고 실행하세요. {data_file_name}")

            #print(f"해당 문서가 열려있습니다. 닫고 다시 시작해주세요. {data_file_name}")

        #wb = openpyxl.load_workbook('result_230420_095250.xlsx')
        
import sys
from enum import Enum, auto
import datetime
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QPushButton, QFileDialog, QTextEdit, QComboBox
from PyQt5.QtCore import QDate

import CLMaker_cashshop as ClCash
import CLMaker_Event as ClEvent
import openpyxl

if __name__ == "__main__" :
    #QApplication : 프로그램을 실행시켜주는 클래스
    app = QApplication(sys.argv) 

    #WindowClass의 인스턴스 생성
    myWindow = WindowClass() 

    #프로그램 화면을 보여주는 코드
    myWindow.show()

    #프로그램을 이벤트루프로 진입시키는(프로그램을 작동시키는) 코드
    app.exec_()