# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '230504.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 267)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(0, 23))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setStyleSheet("background-color: rgb(31, 78,120);\n"
"color: rgb(255, 255, 255);\n"
"font : bold")
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.combox_contents = QtWidgets.QComboBox(self.centralwidget)
        self.combox_contents.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_contents.sizePolicy().hasHeightForWidth())
        self.combox_contents.setSizePolicy(sizePolicy)
        self.combox_contents.setMinimumSize(QtCore.QSize(0, 0))
        self.combox_contents.setMaximumSize(QtCore.QSize(1888888, 23))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.combox_contents.setFont(font)
        self.combox_contents.setStyleSheet("background-color: rgb(155, 194, 230);")
        self.combox_contents.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combox_contents.setIconSize(QtCore.QSize(16, 15))
        self.combox_contents.setPlaceholderText("")
        self.combox_contents.setObjectName("combox_contents")
        self.combox_contents.addItem("")
        self.combox_contents.addItem("")
        self.horizontalLayout.addWidget(self.combox_contents)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMinimumSize(QtCore.QSize(0, 23))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setStyleSheet("background-color: rgb(31, 78,120);\n"
"color: rgb(255, 255, 255);\n"
"font : bold")
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.combox_doctype = QtWidgets.QComboBox(self.centralwidget)
        self.combox_doctype.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_doctype.sizePolicy().hasHeightForWidth())
        self.combox_doctype.setSizePolicy(sizePolicy)
        self.combox_doctype.setMinimumSize(QtCore.QSize(0, 0))
        self.combox_doctype.setMaximumSize(QtCore.QSize(1888888, 23))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.combox_doctype.setFont(font)
        self.combox_doctype.setStyleSheet("background-color: rgb(155, 194, 230);")
        self.combox_doctype.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combox_doctype.setIconSize(QtCore.QSize(16, 15))
        self.combox_doctype.setPlaceholderText("")
        self.combox_doctype.setObjectName("combox_doctype")
        self.combox_doctype.addItem("")
        self.combox_doctype.addItem("")
        self.horizontalLayout_2.addWidget(self.combox_doctype)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setMinimumSize(QtCore.QSize(0, 23))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("background-color: rgb(31, 78,120);\n"
"color: rgb(255, 255, 255);\n"
"font : bold")
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.combox_country = QtWidgets.QComboBox(self.centralwidget)
        self.combox_country.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_country.sizePolicy().hasHeightForWidth())
        self.combox_country.setSizePolicy(sizePolicy)
        self.combox_country.setMinimumSize(QtCore.QSize(0, 0))
        self.combox_country.setMaximumSize(QtCore.QSize(1888888, 23))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.combox_country.setFont(font)
        self.combox_country.setStyleSheet("background-color: rgb(155, 194, 230);")
        self.combox_country.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combox_country.setIconSize(QtCore.QSize(16, 15))
        self.combox_country.setPlaceholderText("")
        self.combox_country.setObjectName("combox_country")
        self.combox_country.addItem("")
        self.combox_country.addItem("")
        self.horizontalLayout_3.addWidget(self.combox_country)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.input_datapath = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_datapath.sizePolicy().hasHeightForWidth())
        self.input_datapath.setSizePolicy(sizePolicy)
        self.input_datapath.setMinimumSize(QtCore.QSize(0, 23))
        self.input_datapath.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.input_datapath.setFont(font)
        self.input_datapath.setDragEnabled(False)
        self.input_datapath.setObjectName("input_datapath")
        self.horizontalLayout_5.addWidget(self.input_datapath)
        self.btn_datapath = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_datapath.sizePolicy().hasHeightForWidth())
        self.btn_datapath.setSizePolicy(sizePolicy)
        self.btn_datapath.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_datapath.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.btn_datapath.setFont(font)
        self.btn_datapath.setStyleSheet("background-color: rgb(155, 194, 230);")
        self.btn_datapath.setObjectName("btn_datapath")
        self.horizontalLayout_5.addWidget(self.btn_datapath)
        self.btn_datapath_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_datapath_2.sizePolicy().hasHeightForWidth())
        self.btn_datapath_2.setSizePolicy(sizePolicy)
        self.btn_datapath_2.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_datapath_2.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.btn_datapath_2.setFont(font)
        self.btn_datapath_2.setStyleSheet("background-color: rgb(155, 194, 230);")
        self.btn_datapath_2.setObjectName("btn_datapath_2")
        self.horizontalLayout_5.addWidget(self.btn_datapath_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.dateedit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateedit.setEnabled(True)
        self.dateedit.setObjectName("dateedit")
        self.verticalLayout.addWidget(self.dateedit)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.progressbar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressbar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.progressbar.setProperty("value", 0)
        self.progressbar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressbar.setTextVisible(True)
        self.progressbar.setObjectName("progressbar")
        self.horizontalLayout_6.addWidget(self.progressbar)
        self.btn_execute = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_execute.sizePolicy().hasHeightForWidth())
        self.btn_execute.setSizePolicy(sizePolicy)
        self.btn_execute.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_execute.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_execute.setFont(font)
        self.btn_execute.setStyleSheet("background-color: rgb(47, 117, 181);\n"
"color: rgb(255, 255, 255);\n"
"font: bold")
        self.btn_execute.setObjectName("btn_execute")
        self.horizontalLayout_6.addWidget(self.btn_execute)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 433, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.combox_contents.setCurrentIndex(0)
        self.combox_doctype.setCurrentIndex(0)
        self.combox_country.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RDM (R2M Document Maker)"))
        self.label_13.setText(_translate("MainWindow", " 컨텐츠"))
        self.combox_contents.setItemText(0, _translate("MainWindow", "유료상점"))
        self.combox_contents.setItemText(1, _translate("MainWindow", "이벤트"))
        self.label_14.setText(_translate("MainWindow", " 문서타입"))
        self.combox_doctype.setItemText(0, _translate("MainWindow", "TC"))
        self.combox_doctype.setItemText(1, _translate("MainWindow", "CL"))
        self.label_15.setText(_translate("MainWindow", " 국가"))
        self.combox_country.setItemText(0, _translate("MainWindow", "KR"))
        self.combox_country.setItemText(1, _translate("MainWindow", "TW"))
        self.input_datapath.setPlaceholderText(_translate("MainWindow", "대상 데이터 파일 경로"))
        self.btn_datapath.setText(_translate("MainWindow", "..."))
        self.btn_datapath_2.setText(_translate("MainWindow", "열기"))
        self.btn_execute.setText(_translate("MainWindow", "실행 (F2)"))
        self.btn_execute.setShortcut(_translate("MainWindow", "F2"))



#복붙시작◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈◈


        self.btn_datapath.clicked.connect(self.select_data_file)
        self.btn_execute.clicked.connect(self.activate)

        self.input_datapath.setAcceptDrops(True)
        self.input_datapath.dragEnterEvent = self.drag_enter_event
        self.input_datapath.dropEvent = self.drop_event

        self.combox_country.currentTextChanged.connect(self.set_data_path)
        self.combox_contents.currentTextChanged.connect(self.set_data_path)
        self.combox_doctype.currentTextChanged.connect(self.set_data_path)
    

#기본동작■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

    def select_data_file(self):
        # Open a file dialog to select the data file
        file_filter = "Video files (*.mp4 *.mkv)"
        file_filter = "엑셀 파일 (*.xlsx)"

        data_file, _ = QFileDialog.getOpenFileName(MainWindow,"데이터 파일 선택", filter= file_filter)
        self.input_datapath.setText(data_file)

    def drag_enter_event(self, event):
        # 드래그앤드랍 가능한 MIME 타입인지 체크
        if event.mimeData().hasUrls():
            event.accept()
        else:
            event.ignore()
    
    def drop_event(self, event):
        # 파일 경로를 가져와서 QLineEdit에 입력
        urls = event.mimeData().urls()
        file_path = urls[0].toLocalFile()
        self.input_datapath.setText(file_path)

    def set_data_path(self):
        contents = self.combox_contents.currentText()
        country = self.combox_country.currentText()

        self.input_datapath.setText(f"{contents}DATA_{country}.xlsx")




#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
    def activate(self):

        if self.combox_contents.currentText() == "유료상점" and self.combox_doctype.currentText() == "CL" :

            data = ClCash.extract_data_cashshop("유료상점DATA_KR.xlsx","2023-04-27")
            xlFileName = ClCash.write_data_cashshop_inspection(data)
            ClCash.postprocess_cashshop(xlFileName)

        #wb = openpyxl.load_workbook('result_230420_095250.xlsx')
        



from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QPushButton, QFileDialog, QTextEdit, QComboBox
import CLMaker_cashshop as ClCash
import CLMaker_Event as ClEvent

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())






